project_id = "pigavlxphdpjsjiwohok"

[functions.delete-account]
verify_jwt = true

[functions.weekly-summary]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.fetch-admin-stats]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.elevenlabs-transcribe]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
