project_id = "pigavlxphdpjsjiwohok"

[functions.delete-account]
verify_jwt = true

[functions.weekly-summary]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
